// server/planning/engines/estate.ts
import type { EstateInputs, EstateAnalysis, EstateRecommendation } from "../types.js";
import { calculateFederalTax, calculateProvincialTax, calculateProbateFees, getMarginalRate } from "../data/taxData2024.js";

export function analyzeEstate(inputs: EstateInputs, locale = "en"): EstateAnalysis {
  const { province, age, maritalStatus, primaryResidence, cottageOrSecondProperty, rrspBalance, rrifBalance, tfsaBalance, nonRegInvestments, lifeInsurance, businessInterest, otherAssets, mortgage, otherDebt, hasWill, hasPOA, hasHCDirective, namedRrspBeneficiary, namedTfsaBeneficiary, namedInsuranceBeneficiary, rrspTaxableOnDeath, capitalGainsOnCottage, capitalGainsOnBusiness } = inputs;
  const grossEstate = primaryResidence + cottageOrSecondProperty + rrspBalance + rrifBalance + tfsaBalance + nonRegInvestments + lifeInsurance + businessInterest + otherAssets;
  const totalLiabilities = mortgage + otherDebt, netEstate = grossEstate - totalLiabilities;
  const bypassingProbate = tfsaBalance + (namedRrspBeneficiary?rrspBalance+rrifBalance:0) + (namedInsuranceBeneficiary?lifeInsurance:0) + (maritalStatus==="married"?primaryResidence:0);
  const subjectToProbate = Math.max(0, netEstate - bypassingProbate);
  const probateFees = calculateProbateFees(subjectToProbate, province);
  const marginalRate = getMarginalRate(rrspBalance, province);
  const taxOnRrsp = rrspTaxableOnDeath ? Math.round(calculateFederalTax(rrspBalance+rrifBalance)+calculateProvincialTax(rrspBalance+rrifBalance,province)) : 0;
  const taxableCapGains = (capitalGainsOnCottage + capitalGainsOnBusiness) * 0.50;
  const taxOnCapGains = Math.round(calculateFederalTax(taxableCapGains) + calculateProvincialTax(taxableCapGains, province));
  const totalTaxOnDeath = taxOnRrsp + taxOnCapGains;
  const toSpouse = maritalStatus==="married" ? rrspBalance+rrifBalance+(namedInsuranceBeneficiary?lifeInsurance:0) : 0;
  const toEstate = netEstate - toSpouse;
  const estimatedLiquidityNeeded = totalTaxOnDeath + probateFees + 25000;
  const lifeInsuranceSuggested = Math.max(0, estimatedLiquidityNeeded - lifeInsurance);
  const recommendations: EstateRecommendation[] = [];
  if (!hasWill) recommendations.push({ priority:"immediate", category:"Will", recommendation:"You do not have a current Will. Dying intestate means your estate is distributed under provincial law, which may not reflect your wishes. Consult an estate lawyer immediately.", estimatedSaving:Math.round(netEstate*0.03) });
  if (!hasPOA) recommendations.push({ priority:"immediate", category:"Power of Attorney", recommendation:"A Power of Attorney for Property and Personal Care is essential. Without one, your family may need to apply to court for guardianship, which is costly and time-consuming.", estimatedSaving:5000 });
  if (!namedRrspBeneficiary && (rrspBalance+rrifBalance)>0) recommendations.push({ priority:"high", category:"RRSP/RRIF Beneficiary", recommendation:`Name your spouse as the direct beneficiary of your RRSP/RRIF ($${(rrspBalance+rrifBalance).toLocaleString()}). This allows a tax-deferred rollover and bypasses probate.`, estimatedSaving:Math.round(probateFees) });
  if (cottageOrSecondProperty > 0 && capitalGainsOnCottage > 0) recommendations.push({ priority:"high", category:"Secondary Property", recommendation:`Your cottage has an unrealized capital gain of $${capitalGainsOnCottage.toLocaleString()}. Consider a life insurance policy or estate freeze to minimize the tax liability on death.`, estimatedSaving:Math.round(taxableCapGains*marginalRate*0.3) });
  if (lifeInsuranceSuggested > 0) recommendations.push({ priority:"medium", category:"Estate Liquidity", recommendation:`Your estate may face a liquidity shortfall of $${estimatedLiquidityNeeded.toLocaleString()} for taxes and fees. Consider a $${lifeInsuranceSuggested.toLocaleString()} life insurance policy to provide tax-free liquidity.`, estimatedSaving:lifeInsuranceSuggested });
  return { grossEstate:Math.round(grossEstate), totalLiabilities:Math.round(totalLiabilities), netEstate:Math.round(netEstate), probateFees:Math.round(probateFees), probateRate:subjectToProbate>0?probateFees/subjectToProbate:0, assetsBypassingProbate:Math.round(bypassingProbate), assetsSubjectToProbate:Math.round(subjectToProbate), probateMinimizationSavings:Math.round(calculateProbateFees(netEstate,province)-probateFees), taxOnRrsp, taxOnCapitalGains:taxOnCapGains, totalTaxOnDeath, effectiveTaxRate:netEstate>0?Math.round(totalTaxOnDeath/netEstate*10000)/10000:0, toSpouse:Math.round(toSpouse), toEstate:Math.round(toEstate), estateAfterTaxAndProbate:Math.max(0,Math.round(toEstate-totalTaxOnDeath-probateFees)), documentStatus:{will:{hasDocument:hasWill,recommendation: locale==="fr" ? (hasWill ? "Le testament est en place. Révisez-le tous les 3 à 5 ans ou après un événement majeur." : "URGENT : Préparez un testament immédiatement.") : (hasWill ? "Will is in place. Review every 3–5 years or after major life events." : "URGENT: Prepare a Will immediately.")},poa:{hasDocument:hasPOA,recommendation: locale==="fr" ? (hasPOA ? "La procuration est en place." : "URGENT : Préparez une procuration pour les biens et les soins personnels.") : (hasPOA ? "POA is in place." : "URGENT: Prepare a POA for property and personal care.")},hcDirective:{hasDocument:hasHCDirective,recommendation: locale==="fr" ? (hasHCDirective ? "La directive médicale est en place." : "Préparez une directive médicale pour préciser vos souhaits.") : (hasHCDirective ? "Healthcare directive is in place." : "Prepare a healthcare directive to specify your medical wishes.")},rrspBeneficiary:{hasDocument:namedRrspBeneficiary,recommendation: locale==="fr" ? (namedRrspBeneficiary ? "Le bénéficiaire du REER/FERR est désigné." : "Désignez un bénéficiaire sur votre REER/FERR pour éviter l'homologation.") : (namedRrspBeneficiary ? "RRSP/RRIF beneficiary is named." : "Name a beneficiary on your RRSP/RRIF to avoid probate.")},tfsaBeneficiary:{hasDocument:namedTfsaBeneficiary,recommendation: locale==="fr" ? (namedTfsaBeneficiary ? "Le titulaire successeur du CELI est désigné." : "Désignez un titulaire successeur sur votre CELI.") : (namedTfsaBeneficiary ? "TFSA successor holder is named." : "Name a successor holder on your TFSA.")},insuranceBeneficiary:{hasDocument:namedInsuranceBeneficiary,recommendation: locale==="fr" ? (namedInsuranceBeneficiary ? "Le bénéficiaire d'assurance est désigné." : "Désignez un bénéficiaire sur toutes vos polices d'assurance.") : (namedInsuranceBeneficiary ? "Insurance beneficiary is named." : "Name a beneficiary on all insurance policies.")}}, recommendations, estimatedLiquidityNeeded:Math.round(estimatedLiquidityNeeded), lifeInsuranceSuggested:Math.round(lifeInsuranceSuggested) };
}